{ pkgs }: {
  deps = [
    pkgs.python310Full
    pkgs.libGL
    pkgs.libxkbcommon
    pkgs.xorg.libX11
    pkgs.xorg.libXext
    pkgs.xorg.libXfixes
    pkgs.xorg.libXrender
    pkgs.xorg.libXtst
    pkgs.xorg.libXi
    pkgs.xorg.libXcursor
    pkgs.xorg.libXdamage
    pkgs.xorg.libXrandr
    pkgs.xorg.libXinerama
    pkgs.xorg.libXcomposite
    pkgs.xorg.libxcb
    pkgs.alsa-lib
    pkgs.mesa
    pkgs.atk
    pkgs.cairo
    pkgs.cups
    pkgs.dbus
    pkgs.expat
    pkgs.fontconfig
    pkgs.freetype
    pkgs.gdk-pixbuf
    pkgs.glib
    pkgs.gtk3
    pkgs.harfbuzz
    pkgs.pango
    pkgs.nspr
    pkgs.nss
    pkgs.poppler_utils
  ];
}